### ISSUE TITLE
Use midddleman-vcs-time with 

### ISSUE THREAD

**Issue by it-praktyk** [AndrewKvalheim/middleman-vcs-time#2]
Hi

I tried use middleman-vcs-time with Middleman 4.1.8 but after activation of vcs_time middleman crash with errors like below.

```
[user@host blog]$ bundle exec middleman
bundler: failed to load command: middleman (/usr/local/bin/middleman)
Bundler::GemRequireError: There was an error while trying to load the gem 'middleman-vcs-time'.
Gem Load Error is: undefined method `register' for Middleman::VCSTime::Extension:Class
Backtrace for gem load error is:
/home/user/.gem/ruby/gems/middleman-vcs-time-0.0.2/lib/middleman-vcs-time.rb:3:in `<top (required)>'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `require'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
/home/user/.gem/ruby/gems/middleman-core-4.1.8/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
/home/user/.gem/ruby/gems/middleman-core-4.1.8/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
/home/user/.gem/ruby/gems/middleman-cli-4.1.8/bin/middleman:10:in `<top (required)>'
/usr/local/bin/middleman:23:in `load'
/usr/local/bin/middleman:23:in `<top (required)>'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `load'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:24:in `run'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/cli.rb:304:in `exec'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
/home/user/.gem/ruby/gems/bundler-1.12.4/exe/bundle:27:in `block in <top (required)>'
/home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/user/.gem/ruby/gems/bundler-1.12.4/exe/bundle:19:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Bundler Error Backtrace:

  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
  /home/user/.gem/ruby/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
  /home/user/.gem/ruby/gems/middleman-core-4.1.8/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
  /home/user/.gem/ruby/gems/middleman-core-4.1.8/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
  /home/user/.gem/ruby/gems/middleman-cli-4.1.8/bin/middleman:10:in `<top (required)>'
  /usr/local/bin/middleman:23:in `load'
  /usr/local/bin/middleman:23:in `<top (required)>'
```

Can you help me?

Thank you in advance.

**Comment by AndrewKvalheim** [comment]
Looks like you picked up an old version that had an [unbound version constraint](https://github.com/AndrewKvalheim/middleman-vcs-time/commit/58159cb181a2ff61045a2a637d82fd18a9f7a978) (oops). Newer versions correctly claim to be [incompatible](https://github.com/AndrewKvalheim/middleman-vcs-time/blob/v0.0.3/middleman-vcs-time.gemspec#L19) with Middleman 4.

I've just released [middleman-vcs-time 0.0.4](https://rubygems.org/gems/middleman-vcs-time/versions/0.0.4), so try a `bundle update` now.
